spring.application.name=authentication-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/authentication-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

spring.kafka.bootstrap-servers=localhost:9092

token.access.secret=your-secret-key-change-in-production
token.access.lifetime=600000
token.refresh.lifetime=2592000000